StylesPath = /app/styles
MinAlertLevel = suggestion
IgnoredScopes = code, tt, img, url, a
SkippedScopes = script, style, pre, figure, code

[formats]
mdx = md

# Vocabularies
Vocab = Mintlify

[*]
BasedOnStyles = Mintlify

[id/**/*.mdx]
BasedOnStyles = ""

[docs/**/*.md]
BasedOnStyles = ""
