openapi: 3.0.3
info:
  title: Neosantara AI Common Components
  version: 1.0.0

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Format "Bearer YOUR_API_KEY" or "x-api-key" header.

  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
            type:
              type: string
            code:
              type: string
            request_id:
              type: string

    Usage:
      type: object
      properties:
        prompt_tokens:
          type: integer
        completion_tokens:
          type: integer
        total_tokens:
          type: integer

    Message:
      type: object
      required: [role, content]
      properties:
        role:
          type: string
          enum: [system, user, assistant, tool]
        content:
          oneOf:
            - type: string
            - type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                    enum: [text, image_url, file]
                  text:
                    type: string
                  image_url:
                    type: object
                    properties:
                      url:
                        type: string
                  file_url:
                    type: object
                    properties:
                      url:
                        type: string

    Reasoning:
      type: object
      properties:
        enabled:
          type: boolean
        effort:
          type: string
          enum: [none, low, medium, high]
        max_tokens:
          type: integer

    Tool:
      type: object
      required: [type, function]
      properties:
        type:
          type: string
          enum: [function]
        function:
          type: object
          required: [name, parameters]
          properties:
            name:
              type: string
            description:
              type: string
            parameters:
              type: object
