openapi: 3.0.3
info:
  title: Neosantara AI - Models API
  description: API for discovering available models and their capabilities.
  version: 1.0.0
servers:
  - url: https://api.neosantara.xyz/v1
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
paths:
  /models:
    get:
      tags: [Models]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  object:
                    type: string
                    example: list
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: string }
                        object: { type: string }
                        created: { type: integer }
                        owned_by: { type: string }
  /models/{modelId}:
    get:
      tags: [Models]
      summary: Retrieve Model
      description: Get detailed information about a specific model.
      parameters:
        - name: modelId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Model Not Found
        '429':
          description: Rate Limit Exceeded
