openapi: 3.0.3
info:
  title: Neosantara AI - User Account API
  description: API for monitoring account balance, usage statistics, and activity logs.
  version: 1.0.0
servers:
  - url: https://api.neosantara.xyz/v1
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
paths:
  /user/usage:
    get:
      tags: [Account]
      summary: Get Account Status
      description: Returns billing mode, current balance or quota, and recent usage logs (last 24 hours).
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  billing:
                    type: object
                  stats_24h:
                    type: object
                  recent_logs:
                    type: array
                    items:
                      type: object
                      properties:
                        timestamp: { type: string }
                        model: { type: string }
                        tokens: { type: integer }
        '401':
          description: Unauthorized
        '429':
          description: Rate Limit Exceeded
